name: UI tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: supersede-css-jlg-enhanced/package-lock.json

      - name: Install dependencies
        working-directory: supersede-css-jlg-enhanced
        run: npm ci

      - name: Install Playwright browsers
        working-directory: supersede-css-jlg-enhanced
        run: npx playwright install --with-deps chromium

      - name: Run Playwright UI tests
        working-directory: supersede-css-jlg-enhanced
        env:
          CI: 'true'
        run: npx playwright test
